from pathlib import Path
from io import StringIO
import contextlib
import sys

from scripts import validate, stats, annotate, public


TEMPLATE = Path("templates/readme.md")
README = Path("readme.md")

STATS_START = "<!-- STATS_START -->"
STATS_END = "<!-- STATS_END -->"


def run_validation():
    print("Running validation...")
    ok = validate.main(return_success=True)
    if not ok:
        print("Validation failed. Aborting build.")
        sys.exit(1)
    print("Validation successful.\n")


def capture_stats_output():
    print("Collecting statistics...")
    stream = StringIO()
    with contextlib.redirect_stdout(stream):
        stats.main()
    output = stream.getvalue().strip()
    print("Statistics collected.\n")
    return output


def update_readme(stats_block: str):
    print("Updating readme.md...")

    if not TEMPLATE.exists():
        print(f"Template file not found: {TEMPLATE}")
        sys.exit(1)

    template_text = TEMPLATE.read_text(encoding="utf-8")

    before, _, remainder = template_text.partition(STATS_START)
    _, _, after = remainder.partition(STATS_END)

    final_stats = f"```\n{stats_block}\n```"
    note = "<!-- This is autogenerated file. Any changes should be done in templates/readme.md and rebuild by build.py -->\n\n"

    new_readme = note + before + final_stats + after
    README.write_text(new_readme, encoding="utf-8")

    print("readme.md updated.\n")


def run_annotations():
    print("Generating annotations...")
    annotate.main()
    print("Annotations generated.\n")


def run_public_build():
    print("Generating public build files...")
    public.main()
    print("Public build files generated.\n")


def main():
    print("Build started.\n")

    run_validation()
    stats_text = capture_stats_output()
    update_readme(stats_text)
    run_annotations()
    run_public_build()

    print("Build completed successfully.")


if __name__ == "__main__":
    main()
